# Generated by Django 5.1.3 on 2024-11-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicGenre', models.CharField(max_length=75)),
                ('movieGenre', models.CharField(max_length=75)),
                ('showGenre', models.CharField(max_length=75)),
            ],
        ),
    ]
