# Generated by Django 5.1.3 on 2024-11-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_favouritegenres_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritegenres',
            name='movieGenre',
            field=models.CharField(choices=[('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('DOCUMENTRY', 'Documentry'), ('MOCKUMENTRY', 'Mockumentry'), ('THRILLER', 'Thriller')], default='COMEDY', max_length=75),
        ),
        migrations.AlterField(
            model_name='favouritegenres',
            name='musicGenre',
            field=models.CharField(choices=[('ROCK', 'Rock and Roll'), ('POP', 'POP'), ('INDIE ROCK', 'Indie/Alt Rock'), ('LOFI', 'Lo-Fi'), ('RAP', 'Rap'), ('BOOMBAP', 'Boombap Rap')], default='MOCKUMENTRY', max_length=75),
        ),
        migrations.AlterField(
            model_name='favouritegenres',
            name='showGenre',
            field=models.CharField(choices=[('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('DOCUMENTRY', 'Documentry'), ('MOCKUMENTRY', 'Mockumentry'), ('THRILLER', 'Thriller')], default='MOCKUMENTRY', max_length=75),
        ),
    ]
