# Generated by Django 5.1.3 on 2024-11-22 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_alter_favouritegenres_moviegenre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=350, verbose_name='bio')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('movieGenre', models.CharField(choices=[('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('DOCUMENTRY', 'Documentry'), ('MOCKUMENTRY', 'Mockumentry'), ('THRILLER', 'Thriller')], default='COMEDY', max_length=75)),
                ('showGenre', models.CharField(choices=[('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('DOCUMENTRY', 'Documentry'), ('MOCKUMENTRY', 'Mockumentry'), ('THRILLER', 'Thriller')], default='MOCKUMENTRY', max_length=75)),
                ('musicGenre', models.CharField(choices=[('ROCK', 'Rock and Roll'), ('POP', 'POP'), ('INDIE ROCK', 'Indie/Alt Rock'), ('LOFI', 'Lo-Fi'), ('RAP', 'Rap'), ('BOOMBAP', 'Boombap Rap')], default='MOCKUMENTRY', max_length=75)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
