# Generated by Django 5.1.3 on 2024-11-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_alter_profile_photo_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_images/default-profile-picture', upload_to='profile_images'),
        ),
    ]
