# Generated by Django 5.1.3 on 2024-11-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0008_alter_profile_showgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='showGenre',
            field=models.CharField(choices=[(10759, 'Action & Adventure'), (16, 'Animation'), (35, 'Comedy'), (80, 'Crime'), (99, 'Documentary'), (18, 'Drama'), (10751, 'Family'), (10762, 'Kids'), (9648, 'Mystery'), (10763, 'News'), (10764, 'Reality'), (10765, 'Sci-Fi & Fantasy'), (10766, 'Soap'), (10767, 'Talk'), (10768, 'War & Politics'), (37, 'Western')], default='MOCKUMENTRY', max_length=75),
        ),
    ]
