# Generated by Django 5.1.3 on 2024-11-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0011_likedshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='showGenre',
            field=models.CharField(choices=[('COMEDY', 'Comedy'), ('DRAMA', 'Drama'), ('HORROR', 'Horror'), ('DOCUMENTRY', 'Documentry'), ('MOCKUMENTRY', 'Mockumentry'), ('THRILLER', 'Thriller')], default='MOCKUMENTRY', max_length=75),
        ),
    ]
