# Generated by Django 5.1.3 on 2024-11-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0013_alter_profile_bio_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=50, verbose_name='bio'),
        ),
    ]
